name: iOS Build Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the app
      run: |
        xcodebuild clean build \
          -project ReminderApp.xcodeproj \
          -scheme ReminderApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
